name: Build macOS App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Install dependencies (if using CocoaPods)
        run: |
          if [ -f "Podfile" ]; then
            sudo gem install cocoapods
            pod install
          fi
      
      - name: Generate Secrets.xcconfig
        run: |
            echo "CLIENT_ID = $CLIENT_ID" > Secrets.xcconfig
            echo "IS_DEVELOPMENT = false" >> Secrets.xcconfig
            echo "BRANCH = $BRANCH" >> Secrets.xcconfig
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          BRANCH: ${{ github.ref_name }}
    
      - name: Replace secrets
        run: |
            sed -i '' "s/{{ARTIFACT_PAT}}/$ARTIFACT_PAT/g" PCL.Mac/Secrets.swift
        env:
          ARTIFACT_PAT: ${{ secrets.ARTIFACT_PAT }}

      - name: Build Universal Binary (xcodebuild)
        run: |
          PROJECT="PCL.Mac.xcodeproj"
          SCHEME="PCL.Mac"

          if [ -d "$PROJECT" ]; then
            xcodebuild -project "$PROJECT" -scheme "$SCHEME" -configuration Release -archivePath build \
              -xcconfig Secrets.xcconfig \
              ARCHS="arm64 x86_64" ONLY_ACTIVE_ARCH=NO \
              CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO archive
          else
            echo "PCL.Mac.xcodeproj not found!"
            exit 1
          fi

      - name: Copy .app to build/Release
        run: |
          mkdir -p build/Release
          APP_PATH="build.xcarchive/Products/Applications/PCL.Mac.app"
          if [ -d "$APP_PATH" ]; then
            cp -R "$APP_PATH" build/Release/
          else
            echo "PCL.Mac.app not found!"
            exit 1
          fi

      - name: Verify Universal Binary
        run: |
          file build/Release/PCL.Mac.app/Contents/MacOS/PCL.Mac

      - name: Zip PCL.Mac.app
        run: |
          cd build/Release
          zip -r PCL.Mac.zip PCL.Mac.app

      - name: Archive build products
        uses: actions/upload-artifact@v4
        with:
          name: PCL.Mac
          path: build/Release/PCL.Mac.zip
